#URL para configurar este archivo https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
spring:
  banner:
      location: classpath:/banner/banner.txt
#DataBase Properties
  datasource:
    url: jdbc:mysql://192.168.56.103:33060/restspring
    username: root
    password: secret
#hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    hibernate:      ddl-auto: update
    open-in-view: false
#para paginacion de la api de la consulta RestFull
  data:    rest:      page-param-name: page #es el nombre que va a tener en el parametro para pagina
      limit-param-name: limite #es el nombre que va a tener en el parametro para el limite
      default-page-size: 5
      max-page-size: 10 
# propiedades del ResFull
server:
  port: ${PORT:8090}
  error:    whitelabel:      enabled: false
   