#URL para configurar este archivo https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
spring:
  banner:
      location: classpath:/banner/banner.txt
#  thymeleaf: para realizar la configuracion ver en la pagina de configuracion spring.thymeleaf.... todo lo relacionado
#DataBase Properties
  datasource:
    url: jdbc:mysql://192.168.56.103:33060/restspring
    username: root
    password: secret
#hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    hibernate:      ddl-auto: update
    open-in-view: false
server:
#  address: restfull
  port: ${PORT:8090}
  error:    whitelabel:      enabled: false
    